### ISSUE TITLE
Liquid Burner causing game to crash in Create 0.5.1-f for Fabric 0.15.7

### ISSUE THREAD

**Issue by SageofTurtles** [ferriarnus/LiquidBurner#14]
Hello!  I'm using this mod on my server, but when updating the rest of our mods, I saw that it seems to be incompatible and producing an error from Create when Liquid Burner is installed.  I'm attaching the crash report, but please let me know if there's anything else I can provide to help with troubleshooting.  I'm wondering if perhaps this mod just needs to be updated to Create Fabric 0.5.1-f?

[crash-2024-03-29_19.17.48-client.txt](https://github.com/ferriarnus/LiquidBurner/files/14809326/crash-2024-03-29_19.17.48-client.txt)

**Comment by lenamerkli** [comment]
[Current situation on the 11th of April (UTC)]

The mod is indeed incompatible with the latest version of the create mod. `ferriarnus`, the original mod developer and maintainer has not updated it yet, but someone else, `solonovamax`, has a modified copy which works together with the latest create mod version. Check it out here: https://github.com/solonovamax/LiquidBurner/tree/fabric-1.20.1 . Note: You have to compile the mod yourself.

**Comment by SageofTurtles** [comment]
> [Current situation on the 11th of April (UTC)]
> 
> The mod is indeed incompatible with the latest version of the create mod. `ferriarnus`, the original mod developer and maintainer has not updated it yet, but someone else, `solonovamax`, has a modified copy which works together with the latest create mod version. Check it out here: https://github.com/solonovamax/LiquidBurner/tree/fabric-1.20.1 . Note: You have to compile the mod yourself.

Thanks for that! But I don't know anything about creating or compiling mods, so I wouldn't know how to compile that. Any chance you'd be able to give me a walkthrough of how to do it? Or a link to download a .jar that's already compiled?

**Comment by lenamerkli** [comment]
> > [Current situation on the 11th of April (UTC)]
> > The mod is indeed incompatible with the latest version of the create mod. `ferriarnus`, the original mod developer and maintainer has not updated it yet, but someone else, `solonovamax`, has a modified copy which works together with the latest create mod version. Check it out here: https://github.com/solonovamax/LiquidBurner/tree/fabric-1.20.1 . Note: You have to compile the mod yourself.
> 
> Thanks for that! But I don't know anything about creating or compiling mods, so I wouldn't know how to compile that. Any chance you'd be able to give me a walkthrough of how to do it? Or a link to download a .jar that's already compiled?

Downloadable jar (zipped due to github): 
[liquidburner-1.20.1-0.5-merkli-1.zip](https://github.com/ferriarnus/LiquidBurner/files/14970439/liquidburner-1.20.1-0.5-merkli-1.zip)

It is bad practice and not recommended to download executables from any comments sections, so I've provided a tutorial how to compile a minecraft mod (in this case liquid-burner) for yourself on debian/linux (I don't have much experiance with microsoft windows, but I hope its similar):
- Install [git](https://git-scm.com/download/linux) and [Intelij Idea Community](https://www.jetbrains.com/idea/download/?section=linux)
- Download the correct branch from the repository: `git clone https://github.com/lenamerkli/LiquidBurner.git -b fabric-1.20.1` A new directory will be created
- Open this directory in Intelij Idea
- Wait until Java has stopped loading (i.e. the progress bar at the bottom right vanishes)
- Select the `Gradle` menu at the top right and select `tasks` and `build`
- After the tasks finishes, the usable jar is in `/build/libs/` or `/.build/libs/`

Sorry for my late answer.

**Comment by lenamerkli** [comment]
The mod has been updated on [modrinth](https://modrinth.com/mod/liquid-burner/version/1.20.1-0.5-fabric). This issue should be marked as done.
